### ISSUE TITLE
Library not ready for AOT

### ISSUE THREAD

**Issue by echo8795** [AndrewPoyntz/time-ago-pipe#3]
This library is not ready for aot compilation by ngc. It throws this error during AOT compilation
`Error: Unexpected value 'TimeAgoPipe' declared by the module 'AppModule'`

From what ic ould find its missing a file called ".metadat.json". It is required for aot compilation of any angular 2 library. You can read it all about here - 
https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.dugqwr8za

**Comment by AndrewPoyntz** [comment]
@echo8795 Thanks - I will look into at making it AoT friendly as soon as I get a bit of time. The article certainly looks like it'll be useful!

**Comment by arknotts** [comment]
Just PR'd this :slightly_smiling_face: https://github.com/AndrewPoyntz/time-ago-pipe/pull/4

**Comment by AndrewPoyntz** [comment]
1.2.0 now published with this in - thanks again!

**Comment by arknotts** [comment]
@AndrewPoyntz Just noticed, it doesn't like compiling in a project with AoT unless the `*.metadata.json` files are included in the npm package. Once I copied the two in manually it worked fine. Is there a way the build process could include these into the npm package?

**Comment by AndrewPoyntz** [comment]
@arknotts yes, sorry I did the publish in a rush & messed it up - good spot! I've just pushed 1.2.1 out which should have them in

**Comment by arknotts** [comment]
Works great now, thanks!
